name: 'App Shield protect'
description: 'Secure your Android and iOS mobile apps with proven in-app protection including obfuscation, device checks and anti-tamper'
author: 'Verimatrix'
branding:
  icon: upload-cloud
  color: purple
inputs:
  api-key-secret:
    description: 'API Key Secret'
    deprecationMessage: 'This GH action is deprecated. Please use APS command line wrapper directly https://pypi.org/project/vmx-aps/'
    required: true
  api-gateway-url:
    description: 'Optional API Gateway URL'
    deprecationMessage: 'This GH action is deprecated. Please use APS command line wrapper directly https://pypi.org/project/vmx-aps/'
    required: false
  access-token-url:
    description: 'Optional Access Token URL'
    deprecationMessage: 'This GH action is deprecated. Please use APS command line wrapper directly https://pypi.org/project/vmx-aps/'
    required: false
  subscription-type:
    description: 'Optional Subscription Type'
    deprecationMessage: 'This GH action is deprecated. Please use APS command line wrapper directly https://pypi.org/project/vmx-aps/'
    required: false
  app-file:
    description: 'Mobile application file'
    deprecationMessage: 'This GH action is deprecated. Please use APS command line wrapper directly https://pypi.org/project/vmx-aps/'
    required: true

outputs:
  protected-file:
    description: 'Protected application file name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_SECRET: ${{ inputs.api-key-secret }}
    API_GATEWAY_URL: ${{ inputs.api-gateway-url }}
    ACCESS_TOKEN_URL: ${{ inputs.access-token-url }}
    SUBSCRIPTION_TYPE: ${{ inputs.subscription-type }}
    APP_FILE: ${{ inputs.app-file }}
