name: "Test"

on:
  push:    

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - uses: ./    # Run itself
        with:
          api-key-secret: ${{ secrets.TEST_KEY }}
          app-file: ./testapp/MoleculesAPK-1.0.apk
          api-gateway-url: https://aps-api.appshield.verimatrixdevcloud.net
          access-token-url: https://ssoapi-ng.platform.verimatrixdevcloud.net/v1/token
          subscription-type: APPSHIELD_PLATFORM
