name: "Test"

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - uses: ./
        with:
          api-key-secret: ${{ secrets.TEST_KEY }}
          app-file: ./MoleculesAPK-1.0.apk
